name: Test and Publish

on:
  push:
    branches:
      - 'main'
      - 'features/**'
      - 'bugs/**'

jobs:
  Test-and-publish:
    name: Test and Publish
    runs-on: windows-latest
    env:
      VERSION: "0.0.${{ github.run_number }}"
    steps:
    - uses: actions/checkout@v4
      name: "Checkout repository"
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
          run: dotnet restore "./src/Dalog.DataPlatform.Client.ImageUploader/Dalog.DataPlatform.Client.ImageUploader/Dalog.DataPlatform.Client.ImageUploader.csproj"   
    - name: Test with dotnet
          run: dotnet test "./tests/Dalog.DataPlatform.Client.ImageUploader/Dalog.DataPlatform.Client.ImageUploader.Tests/Dalog.DataPlatform.Client.ImageUploader.Tests.csproj" --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"  
    - name: Upload dotnet test results
          uses: actions/upload-artifact@v4
          with:
            name: dotnet-results-${{ matrix.dotnet-version }}
            path: TestResults-${{ matrix.dotnet-version }}
          if: ${{ always() }}
    - name: Publish dotnet
      run: dotnet publish "./src/Dalog.DataPlatform.Client.ImageUploader/Dalog.DataPlatform.Client.ImageUploader/Dalog.DataPlatform.Client.ImageUploader.csproj" -c Release -r win-x64 --self-contained -o "./output"